@startuml

title DS12 — Collecter les données
hide footbox
skinparam shadowing false

actor "Administrateur" as A
participant "Frontend" as F
participant "Backend" as B
participant "NASA FIRMS" as N
database "Base de données" as DB

A -> F : Lance la collecte
F -> B : Demander la collecte
B -> N : Récupérer les données manquantes
N --> B : Détections
B -> DB : Enregistrer les nouvelles détections
DB --> B : Confirmation
B --> F : Résultat de la collecte
F --> A : Afficher le résultat

@enduml